// <auto-generated />
namespace Black_Conner_HW5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Checkpoint1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Checkpoint1));
        
        string IMigrationMetadata.Id
        {
            get { return "201703272315443_Checkpoint 1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
